//GET http://localhost:3002/api/drivers?pos=TITULAR

//GET http://localhost:3002/api/drivers/14

DELETE http://localhost:3002/api/drivers/24

//POST http://localhost:3002/api/drivers

//PUT http://localhost:3002/api/drivers/23
Content-Type: application/json

{
    "fullname": "Caramelo Masticable",
    "city": "Miami, Florid, Estados Unidos",
    "birthdate": "1996-06-26T00:00:00.000Z",
    "number_of_wins": 0,
    "number_of_gp": 2,
    "main_sponsor": "Banco Do Brasil",
    "team_id": 2,
    "position": "RESERVA"
}



